"""add_codigo_to_turma

Revision ID: 06638f983323
Revises: b34b9d6f03da
Create Date: 2026-07-07 15:45:06.698431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06638f983323'
down_revision: Union[str, Sequence[str], None] = 'b34b9d6f03da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) adiciona como NULLABLE primeiro (nao quebra as turmas que ja existem)
    op.add_column('turmas', sa.Column('codigo', sa.String(length=50), nullable=True))
    # 2) preenche as turmas existentes com um codigo provisorio unico (TURMA-<id>)
    op.execute("UPDATE turmas SET codigo = 'TURMA-' || id WHERE codigo IS NULL")
    # 3) agora que ninguem esta nulo, torna obrigatorio
    op.alter_column('turmas', 'codigo', existing_type=sa.String(length=50), nullable=False)
    # 4) indice unico
    op.create_index(op.f('ix_turmas_codigo'), 'turmas', ['codigo'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turmas_codigo'), table_name='turmas')
    op.drop_column('turmas', 'codigo')
    # ### end Alembic commands ###
