"""adiciona cpf e data_nascimento ao aluno

Revision ID: 808c99c1db83
Revises: 820b4761496f
Create Date: 2026-06-03 17:30:51.682264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808c99c1db83'
down_revision: Union[str, Sequence[str], None] = '820b4761496f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('cpf', sa.String(length=14), nullable=False))
    op.add_column('alunos', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.alter_column('alunos', 'matricula',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'alunos', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alunos', type_='unique')
    op.alter_column('alunos', 'matricula',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('alunos', 'data_nascimento')
    op.drop_column('alunos', 'cpf')
    # ### end Alembic commands ###
