"""adiciona cpf e titulacao ao docente

Revision ID: 8bea859b015e
Revises: 808c99c1db83
Create Date: 2026-06-05 10:54:05.991500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bea859b015e'
down_revision: Union[str, Sequence[str], None] = '808c99c1db83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docentes', sa.Column('cpf', sa.String(length=14), nullable=False))
    op.add_column('docentes', sa.Column('titulacao', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'docentes', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'docentes', type_='unique')
    op.drop_column('docentes', 'titulacao')
    op.drop_column('docentes', 'cpf')
    # ### end Alembic commands ###
