"""add vagas disponiveis

Revision ID: b34b9d6f03da
Revises: fe4cafdcfb1e
Create Date: 2026-06-08 15:09:29.618771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34b9d6f03da'
down_revision: Union[str, Sequence[str], None] = 'fe4cafdcfb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turmas', sa.Column('vagas_disponiveis', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turmas', 'vagas_disponiveis')
    # ### end Alembic commands ###
