"""add codigo na disciplina

Revision ID: fe4cafdcfb1e
Revises: 8bea859b015e
Create Date: 2026-06-06 13:42:28.158642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4cafdcfb1e'
down_revision: Union[str, Sequence[str], None] = '8bea859b015e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplinas', sa.Column('codigo', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_disciplinas_codigo'), 'disciplinas', ['codigo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplinas_codigo'), table_name='disciplinas')
    op.drop_column('disciplinas', 'codigo')
    # ### end Alembic commands ###
